# Generated by Django 5.1.2 on 2024-11-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.element'),
        ),
    ]
